PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX taxon: <http://purl.uniprot.org/taxonomy/>

SELECT ?nameClone1 ?taxonClone1
WHERE {

    ?taxonClone1 rdf:type up:Taxon.
    ?taxonClone1 up:scientificName ?nameClone1.
    ?taxonClone1 rdfs:subClassOf ?ancestorTaxonClone1.
    

  # Result variable is ?ancestorTaxonClone1
  VALUES ?ancestorTaxonClone1 { taxon:2 } .

}
