PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX up: <http://purl.uniprot.org/core/>

SELECT ?databaseClone1 ?entryClone1
WHERE {
VALUES ?entryTypeClone1 { up:Protein } .
 VALUES ?databaseClone1 { <http://purl.uniprot.org/database/PDB> } .
    ?entryClone1 rdf:type ?entryTypeClone1.
    ?entryClone1 rdfs:seeAlso ?dbentryClone1.
    ?dbentryClone1 up:database ?databaseClone1.
    

  # Result variable is ?databaseClone1
 


  # Result variable is ?entryTypeClone1
  

}
