PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX taxon: <http://purl.uniprot.org/taxonomy/>

SELECT DISTINCT ?entryClone5 ?typeClone6
WHERE {
 VALUES ?typeClone6 { up:Protein } .
   VALUES ?organismClone5 { taxon:9606 } .
    ?entryClone5 up:organism ?organismClone5.
    ?organismClone5 rdfs:subClassOf? ?taxonClone5. # Hierarchy of taxon is materialized
    

  # Result variable is ?organismClone5

 
    ?entryClone5 rdf:type ?typeClone6 .
    

  # Result variable is ?typeClone6
 

}
