PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX up: <http://purl.uniprot.org/core/>

SELECT ?entryClone7 ?pdbIdClone1 ?pdbChainClone1 ?chainClone1
WHERE {

    ?entryClone7 rdf:type ?entryTypeClone7.
    ?entryClone7 rdfs:seeAlso ?pdbClone1.
    #?pdbClone1 up:database ?databaseClone7.
    

  # Result variable is ?databaseClone7
  #VALUES ?databaseClone7 { <http://purl.uniprot.org/database/PDB> } .

 
    ?pdbClone1 up:database <http://purl.uniprot.org/database/PDB> ;
       up:chainSequenceMapping ?mappingProteinClone1 .
    ?mappingProteinClone1 up:chain ?chainsPlusRangeClone1 .
    

  VALUES(?pdbIdClone1 ?pdbChainClone1) {('6VXC' 'A') ('1BG3' 'B')} .
  BIND(iri(concat('http://rdf.wwpdb.org/pdb/', ?pdbIdClone1)) AS ?pdbClone1) .
  BIND(STRBEFORE(?chainsPlusRangeClone1, '=') AS ?chainClone1) .
  FILTER(CONTAINS(?chainClone1, ?pdbChainClone1)) .
    
}
