PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX up: <http://purl.uniprot.org/core/>

SELECT DISTINCT ?entryClone6 ?typeClone6 ?mnemonicClone6 ?oldmnemonicClone6
WHERE {

    ?entryClone6 rdf:type ?typeClone6.
    ?entryClone6 up:mnemonic ?mnemonicClone6.
    OPTIONAL {?entryClone6 up:oldMnemonic ?oldmnemonicClone6.}
    
}
