PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?predicateClone1 ?objectClone1
WHERE {
 
    ?subjectClone1 ?predicateClone1 ?objectClone1 .
    

  # Result variable is ?subjectClone1
  VALUES ?subjectClone1 { <http://purl.uniprot.org/uniparc/UPI000012A0AD> } .

}
