PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX up: <http://purl.uniprot.org/core/>

SELECT DISTINCT ?altLabelClone7 ?geneClone7 ?locusNameClone7 ?orfNameClone7 ?proteinClone7
WHERE {

    ?proteinClone7 rdf:type up:Protein.
    ?proteinClone7 up:encodedBy ?geneClone7.
    ?geneClone7 skos:prefLabel ?nameClone7.
    OPTIONAL {?geneClone7 up:locusName ?locusNameClone7.}
    OPTIONAL {?geneClone7 skos:altLabel ?altLabelClone7.}
    OPTIONAL {?geneClone7 up:orfName ?orfNameClone7.}
    
}
