PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX up: <http://purl.uniprot.org/core/>

SELECT DISTINCT ?altLabelClone9 ?geneClone9 ?locusNameClone9 ?orfNameClone9 ?proteinClone9
WHERE {

    ?proteinClone9 rdf:type up:Protein.
    ?proteinClone9 up:encodedBy ?geneClone9.
    #?geneClone9 skos:prefLabel ?nameClone9.
    #OPTIONAL {?geneClone9 up:locusName ?locusNameClone9.}
    #OPTIONAL {?geneClone9 skos:altLabel ?altLabelClone9.}
    ?geneClone9 up:orfName ?orfNameClone9.
    
}
