PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX up: <http://purl.uniprot.org/core/>

SELECT DISTINCT ?primaryAccessionClone1 ?proteinClone1
WHERE {
 
    ?proteinClone1 rdf:type up:Protein.
    BIND(substr(str(?proteinClone1), strlen(str(uniprotkb:))+1) AS ?primaryAccessionClone1)
    
}
