PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX up: <http://purl.uniprot.org/core/>

SELECT DISTINCT ?annotationClone9 ?diseaseClone9 ?diseaseLabelClone9 ?proteinClone9
WHERE {

    ?proteinClone9 up:annotation ?annotationClone9.
    ?proteinClone9 rdf:type up:Protein.
    ?annotationClone9 rdf:type up:Disease_Annotation.
    ?annotationClone9 up:disease ?diseaseClone9.
    ?diseaseClone9 skos:prefLabel ?diseaseLabelClone9.
    ?diseaseClone9 rdf:type up:Disease.
    
}
