PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX : <http://biographs.org/>
PREFIX rh: <http://rdf.rhea-db.org/>

SELECT (COUNT( ?proteinClone28) AS ?truc)
WHERE {

    ?proteinClone28 rdf:type up:Protein .
    ?proteinClone28 up:annotation ?annotationClone28.
    ?annotationClone28 up:catalyticActivity ?catalyticActivityClone28.
    ?catalyticActivityClone28 rdf:type up:Catalytic_Activity .
    ?catalyticActivityClone28 up:catalyzedReaction ?reactionClone28.
    ?annotationClone28 rdf:type up:Catalytic_Activity_Annotation.
    

  SERVICE <https://sparql.rhea-db.org/sparql> {
  # Result variable is ?reactionClone28
  
    ?compoundClone13 (rh:chebi|(rh:reactivePart/rh:chebi)|(rh:underlyingChebi)) ?chebiClone13 .
    ?chebiClone13 (rdfs:subClassOf)* ?chebiAncestorClone13.
    

  # Result variable is ?chebiAncestorClone13
  VALUES ?chebiAncestorClone13 { CHEBI:18059 } .


    ?reactionClone28 rdfs:subClassOf rh:Reaction.
    ?reactionClone28 rh:side ?sideClone14.
    ?sideClone14 rh:contains ?participantClone14.
    ?participantClone14 rh:compound ?compoundClone13.
    
 
   ?reactionClone28 rh:isTransport true .
    
  } .


    ?proteinClone28 up:organism ?organismClone36.
    #?organismClone36 rdfs:subClassOf? ?taxonClone36. # Hierarchy of taxon is materialized
    

  # Result variable is ?organismClone36
  VALUES ?organismClone36 { taxon:9606 } .


    ?proteinClone28 rdf:type up:Protein ;
      #up:created ?creationDateClone20 ;
      #up:modified ?modificationDateClone20 ;
      up:reviewed ?reviewedClone20 ;
      #up:version ?versionClone20 .
    

  # Result variable is ?reviewedClone20
  VALUES ?reviewedClone20 { true } .

}
