# Count the number of connections with each of the other modules

PREFIX up: <http://purl.uniprot.org/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <https://sparql_module.biographs.org/> 
PREFIX up_mod: <http://uniprot_module.biographs.org/> 

SELECT ?module ?connected_module (COUNT(DISTINCT ?connection) AS ?connections)
WHERE {

?query rdf:type :SPARQL_Module_Composition.
?query :hasConnection ?connection.
?connection :connects ?port1.
?connection :connects ?port2.

?instance1 :output ?port1.
?instance1 :clonedFrom ?module.

?instance2 :output ?port2.
?instance2 :clonedFrom ?connected_module.

FILTER (?port1 != ?port2).
}
GROUP BY ?module ?connected_module ORDER BY ?connections
